<a href="https://colab.research.google.com/github/Xushnudbek76/AI/blob/main/students_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv('/Student_performance_data _.csv')

# print("first 5:", df.head())

# print(df.describe())
# print(df.info())
df[["Absences", "GPA"]].max()

Absences    29.0
GPA          4.0
dtype: float64

In [18]:
df[["Absences", "GPA"]].mean()

Absences    14.541388
GPA          1.906186
dtype: float64

In [19]:
df[["Absences", "GPA"]].corr()

          Absences       GPA
Absences  1.000000 -0.919314
GPA      -0.919314  1.000000

In [29]:
df1 = pd.read_csv('/content/StudentsPerformance.csv')

In [30]:
df1["total score"] = df1[["math score", "reading score", "writing score"]].sum(axis=1)
df1["average score"] = df1["total score"] / 3
df1["passed"] = np.where(df1["average score"] >= 50, "Yes", "No")

print("New columns preview (total, average, passed):")
print(df1[["total score", "average score", "passed"]].head())

New columns preview (total, average, passed):
   total score  average score passed
0          218      72.666667    Yes
1          247      82.333333    Yes
2          278      92.666667    Yes
3          148      49.333333     No
4          229      76.333333    Yes

In [40]:
test_prep_group = df1.groupby('test preparation course')[['math score', 'reading score', 'writing score']].mean()

print("student score by test preparation course:")
print(test_prep_group)



gender_avg = df1.groupby("gender")[["math score", "reading score", "writing score"]].mean()

print("student score by gender:")
print(gender_avg)

pass_rate = df1["passed"].value_counts(normalize=True) * 100

print("pass rate:")
print(pass_rate)

student score by test preparation course:
                         math score  reading score  writing score
test preparation course
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673
student score by gender:
        math score  reading score  writing score
gender
female   63.633205      72.608108      72.467181
male     68.728216      65.473029      63.311203
pass rate:
passed
Yes    89.7
No     10.3
Name: proportion, dtype: float64

In [44]:
scores = df1[["math score", "reading score", "writing score"]]


print("Numpy Mean:", np.mean(scores, axis=0))
print("Numpy Std:", np.std(scores, axis=0))

z_score = (scores - np.mean(scores, axis=0)) / np.std(scores, axis=0)

print("Z-score:")
print(z_score.head())

Numpy Mean: math score       66.089
reading score    69.169
writing score    68.054
dtype: float64
Numpy Std: math score       15.155497
reading score    14.592890
writing score    15.188057
dtype: float64
Z-score:
   math score  reading score  writing score
0    0.390024       0.193999       0.391492
1    0.192076       1.427476       1.313269
2    1.577711       1.770109       1.642475
3   -1.259543      -0.833899      -1.583744
4    0.653954       0.605158       0.457333

In [49]:
top_scorers = df1[df1["average score"] >= 90];
print("Top scorers", top_scorers.head())

failed_scorers = df1[df1["passed"] == "No"];
print("Failed scorers", failed_scorers.head())

Top scorers      gender race/ethnicity parental level of education     lunch  \
2    female        group B             master's degree  standard
6    female        group B                some college  standard
104    male        group C                some college  standard
106  female        group D             master's degree  standard
114  female        group E           bachelor's degree  standard

    test preparation course  math score  reading score  writing score  \
2                      none          90             95             93
6                 completed          88             95             92
104               completed          98             86             90
106                    none          87            100            100
114               completed          99            100            100

     total score  average score passed
2            278      92.666667    Yes
6            275      91.666667    Yes
104          274      91.333333    Yes
106          287      95.666667    Yes
114          299      99.666667    Yes
Failed scorers     gender race/ethnicity parental level of education         lunch  \
3     male        group A          associate's degree  free/reduced
7     male        group B                some college  free/reduced
9   female        group B                 high school  free/reduced
11    male        group D          associate's degree      standard
17  female        group B            some high school  free/reduced

   test preparation course  math score  reading score  writing score  \
3                     none          47             57             44
7                     none          40             43             39
9                     none          38             60             50
11                    none          40             52             43
17                    none          18             32             28

    total score  average score passed
3           148      49.333333     No
7           122      40.666667     No
9           148      49.333333     No
11          135      45.000000     No
17           78      26.000000     No